name: Assign CODEOWNERS (bearycool11) and Manage Ruleset

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        description: 'The owner of the repo (username or org name)'
        required: true
        default: ${{ github.repository_owner }}
      repo_name:
        description: 'The name of the repo'
        required: true
        default: ${{ github.repository }}
      ruleset_name:
        description: 'The name of the ruleset to update'
        required: true
        default: 'your-ruleset-name'
      user_to_add:
        description: 'The GitHub username to add with write permissions'
        required: true
        default: 'bearycool11'

permissions:
  contents: write
  admin: write

jobs:
  manage_repo:
    name: Manage Repository Settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update Ruleset via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          REPO_OWNER=${{ github.event.inputs.repo_owner }}
          REPO_NAME=${{ github.event.inputs.repo_name }}
          RULESET_NAME=${{ github.event.inputs.ruleset_name }}
          USER_TO_ADD=${{ github.event.inputs.user_to_add }}

          # Fetch the current ruleset
          ruleset_id=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/rulesets" | \
            jq -r --arg name "$RULESET_NAME" '.[] | select(.name==$name) | .id')
          
          # If ruleset not found, exit with message
          if [ -z "$ruleset_id" ]; then
            echo "No ruleset with the specified name found"
            exit 1
          fi

          # Update the ruleset to add write permissions for the specified user
          curl -s -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"bypass_actors": {"users": ["'"$USER_TO_ADD"'"]}}' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/rulesets/$ruleset_id"

          echo "Ruleset updated for $USER_TO_ADD with write access"

      - name: Create CODEOWNERS file
        run: |
          # Example content for CODEOWNERS file
          echo "* @${{ github.event.inputs.user_to_add }}" > .github/CODEOWNERS
          echo "docs/* @docs-team" >> .github/CODEOWNERS
          echo "scripts/* @script-maintainers" >> .github/CODEOWNERS

      - name: Commit and push CODEOWNERS file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/CODEOWNERS
          git commit -m "Add CODEOWNERS file"
          git push origin main

      - name: Post-completion message
        run: |
          echo "Congratulations friend, you've completed this course!"
          echo "celebrate"
          echo "As you continue working on GitHub, remember that high quality reviews improve your projects. If you are new to a repository, inquire about what review practices they have so you can hit the ground running."
          echo "Here's a recap of all the tasks you've accomplished in your repository:"
          echo "  - You learned how to assign pull requests for review."
          echo "  - You left a review on a pull request."
          echo "  - You suggested changes to a pull request."
          echo "  - You applied suggested changes to a pull request."
          echo "What's next?"
          echo "  - Try adding a CODEOWNERS file to your project to automatically assign reviewers to pull requests."
          echo "  - We'd love to hear what you thought of this course in our discussion board."
          echo "  - Take another GitHub Skills course."
          echo "  - Read the GitHub Getting Started docs."
          echo "  - To find projects to contribute to, check out GitHub Explore."
          echo "Get help: Post in our discussion board • Review the GitHub status page"
          echo "© 2023 GitHub • Code of Conduct • MIT License"


name: Ensure Bearycool11 in CODEOWNERS

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        description: 'The owner of the repo (username or org name)'
        required: true
        default: ${{ github.repository_owner }}
      repo_name:
        description: 'The name of the repo'
        required: true
        default: ${{ github.repository }}

permissions:
  contents: write
  admin: write

jobs:
  manage_repo:
    name: Manage Repository CODEOWNERS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          repository: ${{ github.event.inputs.repo_owner }}/${{ github.event.inputs.repo_name }}

      - name: Ensure CODEOWNERS file exists
        run: |
          mkdir -p .github
          if [ ! -f .github/CODEOWNERS ]; then
            touch .github/CODEOWNERS
          fi

      - name: Add Bearycool11 to CODEOWNERS
        run: |
          # Check if bearycool11 is already in the file
          if ! grep -q "bearycool11" .github/CODEOWNERS; then
            # Add bearycool11 to the beginning of the file for all files
            sed -i '1s/^/* @bearycool11\n/' .github/CODEOWNERS
          fi

      - name: Commit and push CODEOWNERS file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          if git diff --quiet .github/CODEOWNERS; then
            echo "No changes to CODEOWNERS file"
          else
            git add .github/CODEOWNERS
            git commit -m "Ensure bearycool11 is in CODEOWNERS"
            git push origin main
          fi

      - name: Post-completion message
        run: |
          echo "Bearycool11 has been added or confirmed in the CODEOWNERS file for this repository."